gym/gym/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webSite.urls', namespace='webSite')),
    path('registration/login/', auth_views.LoginView.as_view(),{'template_name':'login.html'} , name='login'),
    path('registration/logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),

              ]  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gym/webSite/urls.py
from django.urls import path

from . import views

app_name = 'webSite'
urlpatterns = [
    # path('', views.IndexView.as_view(), name='index'), #fix this
    # path('<int:pk>/', views.ManagerDetailView.as_view(), name='detail'), #fix this too

#     path('register/', views.register, name='register'),
#     # path('edit_profile/', views.edit_profile, name='edit_profile'),
#     path('schedule/', views.ScheduleCreate.as_view(template_name='change_list.html'), name='change_list'),
#
#     path('company_create/', views.company_create, name='company_create'),
     path('', views.HomeView.as_view(), name='home'),
     path('companies', views.CompanyList.as_view(), name='company_list'),
     path('companies/<int:pk>', views.CompanyDetail.as_view(), name='company_detail'),



     path('gyms', views.GymList.as_view(), name='gym_list'),
     path('gyms/<int:pk>', views.GymDetail.as_view(), name='gym_detail'),
     path('gymclasses/<int:pk>', views.GymClassesDetail.as_view(), name='gymclasses_detail'),
     path('gymclasses', views.GymClassesList.as_view(), name='gymclasses_list'),
     path('gymactivities/<int:pk>', views.GymActivitiesDetail.as_view(), name='gymactivities_detail'),
     path('gymactivities', views.GymActivitiesList.as_view(), name='gymactivities_list'),


     #     path('create', views.CompanyCreate.as_view(), name='company_create'),
#     path('update/<int:pk>', views.CompanyUpdate.as_view(), name='company_update'),
#     path('delete/<int:pk>', views.CompanyDelete.as_view(), name='company_delete'),
#
# #     userProfile Paths
#     path('userProfiles', views.UserProfileList.as_view(), name='profile_list'),
#     path('userProfile/<int:pk>', views.UserProfileDetail.as_view(), name='profile_details'),
#     path('userProfile/<int:pk>/edit', views.ProfileUpdateView.as_view(), name='edit_profile'),
#     path('create', views.UserProfileCreate.as_view(), name='company_create'),
#     path('addmem/', views.addmem, name='addmem'),
# #     userProfile Paths
#     path('gyms', views.GymList.as_view(), name='gym_list'),
#     path('gym/<int:pk>', views.GymDetail.as_view(), name='gym_details'),
#     path('create', views.GymCreate.as_view(), name='gym_details'),
#     path('update/<int:pk>', views.GymUpdate.as_view(), name='gym_list'),
#     path('delete/<int:pk>', views.GymDelete.as_view(), name='company_delete'),
#
# #     gymClasses Paths
#     path('<int:pk>/', views.ActivityDetail.as_view(), name='detail'),
#     path('<int:pk>/results/', views.ResultsView.as_view(), name='result'),
#     path('changePassword', views.ProfileUpdateView.as_view(), name='change_password'),
]

gym/webSite/models.py
import datetime

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User, Group
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Q
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.forms import ModelForm
from django.urls import reverse
from django.utils import timezone
from phone_field import PhoneField



# get_user_model will return the currently active user model

class Profile(Group):
    class Meta:
        proxy = True
        app_label = 'auth'
        # verbose_name = _('Profile')
        verbose_name_plural = "Profiles"

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50, default='DEFAULT VALUE')
    last_name = models.CharField(max_length=50, default='DEFAULT VALUE')
    email = models.EmailField(max_length=70, blank=True, null=True)
    address = models.CharField(max_length=80, default='')
    dob = models.DateField(null=True, blank=True)
    bio = models.TextField(blank=True, help_text="The bio entered by the user.")
    city = models.CharField(max_length=100, default='')
    phone = models.IntegerField(default=0)
    gender = models.CharField(max_length=1, blank=True, null=True, default=None)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            UserProfile.objects.create(user=instance)
# maybe fix those UserProfile signals


    def __str__(self):
        return f'{self.user.first_name} Profile'

    def create_profile(sender, **kwargs):
        if kwargs['created']:
            user_profile = UserProfile.objects.create(user=kwargs['instance'])


class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50, default=None)
    last_name = models.CharField(max_length=50, default=None)
    email = models.EmailField(unique=True, default=None)

    def __str__(self):
        return f'{self.user.first_name} Member'

    class Meta:
        abstract = True

# Now we are going to create class Company
class Company(models.Model):
    class Meta:
        verbose_name_plural = "companies"

    name = models.CharField(max_length=50)
    address = models.CharField(max_length=80)
    email = models.EmailField()
    phone = PhoneField(blank=True, help_text='Contact phone number')
    bio = models.TextField(blank=True, help_text="The bio entered by the company admin")
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default="", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '%s' % self.name


class UserProfileManager(models.Manager):
    # a Company has only one Manager
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                )
    company = models.OneToOneField(Company, on_delete=models.CASCADE, primary_key=True, )

    def __str__(self):
        return "%s Profiles" % self.user.name

    def active(self):
        return super().get_queryset().filter(active=True)

    def expired(self):
        return super().get_queryset().filter(active=False)

    # decorator
    # we use unicode here in case the name is not in ASCII (Arabic, Chinese etc..)
    # def __unicode__(self):
    #     return f'{self.get_full_name()} Profiles'


class Gym(models.Model):
    name = models.CharField(max_length=50, default=None)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # one Company has many Gyms
    company = models.ForeignKey(Company, on_delete=models.CASCADE)
    location = models.CharField(max_length=80)
    email = models.EmailField(unique=True, default='DEFAULT VALUE')
    bio = models.TextField(blank=True, help_text="The bio entered by gym admin.")
    phone = PhoneField(blank=True, help_text='Contact phone number')


    def __str__(self):
        return '%s' % self.name


class GymClasses(models.Model):
    class Meta:
        verbose_name_plural = "gym classes"

    class_name = models.CharField(max_length=255)
    class_capacity = models.IntegerField(default=0)
    class_participants = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    live_date = models.DateTimeField()
    expiry_date = models.DateTimeField()
    active = models.BooleanField()
    belonging_gym = models.ManyToManyField(Gym)


    def clean(self):
        num_capacity = self.class_capacity
        num_participants = self.class_participants
        if num_participants >num_capacity :
            raise ValidationError ('Class Participants are Surpassing the Class Capacity')

    def __str__(self):
        return self.class_name

    def __unicode__(self):
        return self.class_name

    objects = models.Manager()
    UserProfileManager = UserProfileManager()


class GymActivities(models.Model):
    class Meta:
        verbose_name_plural = "Gym Activities"

    class_name = models.ForeignKey(GymClasses, on_delete=models.CASCADE, default="", null=True, blank=True)  # roger
    activity_name = models.CharField(max_length=200, default=None, null=True)
    # choices = models.IntegerField(default=0)  # choices=votes
    schedule_day = models.DateField()
    schedule_time = models.TimeField()
    max_attend = models.IntegerField()
    active = models.BooleanField()
    instructor = models.ForeignKey(User, on_delete=models.CASCADE, default="", null=True, blank=True)


    def clean(self):
        # print(self.instructor.is_active)
        if not self.instructor.is_active :
            raise ValidationError('This Trainer is unavailable at the moment, please select another')


    def __str__(self):
        return self.activity_name


class Schedule(models.Model):
    class Meta:
        verbose_name_plural = "Scheduling"

    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    activity_name = models.ForeignKey(GymActivities, on_delete=models.CASCADE)
    day = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()
    notes = models.TextField(help_text="Textual Notes", blank=True, null=True)



    def check_overlap(self, fixed_start, fixed_end, new_start, new_end):
        overlap = False
        if new_start == fixed_end or new_end == fixed_start:  # edge case
            overlap = False
        elif (new_start >= fixed_start and new_start <= fixed_end) or (
            new_end >= fixed_start and new_end <= fixed_end):  # innner limits
            overlap = True
        elif new_start <= fixed_start and new_end >= fixed_end:  # outter limits
            overlap = True
        return overlap

    def get_absolute_url(self):
        url = reverse('admin:%s_%s_change' % (self._meta.app_label, self._meta.model_name), args=[self.id])
        return u'<a href="%s">%s</a>' % (url, str(self.start_time))


    def clean(self):
        if self.end_time <= self.start_time:
            raise ValidationError('Ending times must be after the starting times')

        events = Schedule.objects.filter(day=self.day)
        if events.exists():
            for event in events:
                if self.check_overlap(event.start_time, event.end_time, self.start_time, self.end_time):
                    raise ValidationError(
                        'There is an overlap with another event: ' + str(event.day) + ', ' + str(
                            event.start_time) + '-' + str(event.end_time))

gym/webSite/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from  .models import UserProfile, Company, Member


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()

        return user


class EditProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('first_name', 'last_name', 'email', 'address', 'bio', 'dob', 'city', 'phone', 'gender', 'image')




class CreateCompany(forms.ModelForm):
    template_name='/company/company_create.html'
    class Meta:
        model = Company
        fields = '__all__'



class MemberForm (forms.ModelForm) :
    class Meta:
        model = Member
        fields = ('first_name', 'last_name', 'email')
    def save (self, user, commit =True) :
        instance = super (MemberForm, self).save(commit= False)
        instance.user = user
        if commit :
            instance.save()
            self.save_mem()
        return instance

gym/webSite/views/company_views.py
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView, View
from django.shortcuts import get_object_or_404, render, redirect
from ..models import Company


class CompanyDetail(DetailView):
    model = Company
    template_name = 'webSite/company_detail.html'


class CompanyList(ListView):
    model = Company
    context_object_name = "companies"
    template_name = 'webSite/company_list.html'

gym/webSite/views/gym_views.py
from django.views.generic import CreateView, DetailView, ListView, UpdateView, DeleteView, View
from django.shortcuts import get_object_or_404, render, redirect
from ..models import Gym

class GymDetail(DetailView):
    model = Gym
    template_name = 'webSite/gym_detail.html'

class GymList(ListView):
    model = Gym
    context_object_name = "gyms"
    template_name = 'webSite/gym_list.html'

gym/webSite/views/gymactivities_views.py
from django.views.generic import  DetailView, ListView, View
from django.shortcuts import get_object_or_404, render, redirect
from ..models import GymActivities

class GymActivitiesDetail(DetailView):
    model = GymActivities
    template_name = 'webSite/gymactivities_detail.html'

class GymActivitiesList(ListView):
    model = GymActivities
    context_object_name = "gymactivities"
    template_name = 'webSite/gymactivities_list.html'

gym/webSite/views/gymclasses_views.py
from django.views.generic import  DetailView, ListView, View
from django.shortcuts import get_object_or_404, render, redirect
from ..models import GymClasses
from django.db.models import Count

class GymClassesDetail(DetailView):
    model = GymClasses
    template_name = 'webSite/gymclasses_detail.html'

class GymClassesList(ListView):
    model = GymClasses
    context_object_name = "gymclasses"
    Comp_Devices = GymClasses.objects.annotate(no_of_classes=Count('class_name'))
    template_name = 'webSite/gymclasses_list.html'

gym/webSite/views/home_view.py
from django.views.generic import View
from django.shortcuts import get_object_or_404, render, redirect
from ..models import Company



class HomeView(View):
    template_name = 'webSite/home.html'

    def get(self, request, *args, **kwargs):
        name_company = Company.objects.order_by('name_company')
        context= dict(latest_user=name_company)

        return render(request, self.template_name, context)

gym/webSite/templates/webSite/acc_active_email.html
{% autoescape off %}
{% load i18n %}
<h4>
{% trans 'Hi' %} {{ user.account.name }}
</h4>
<p>
{% trans 'Please click on the link below to confirm your registration' %}:
<a href="http://{{ domain }}{% url 'accounts:user-activate' uidb64=uid token=token %}">
    {% trans 'link' %}
</a>
</p>
{% endautoescape %}

gym/webSite/templates/webSite/acc_reactive_email.html
{% autoescape off %}
Hi {{ user.username }},
{% Your address mail has been changed %}
{% Please click on the link below to confirm your changes: %}

http://{{ domain }}{% url 'accounts:user-activate' uidb64=uid token=token %}

{% endautoescape %}

gym/webSite/templates/webSite/company_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% block title %} {% trans "View Company Info" %} {% endblock %}
{% block specific_css %}
<!-- BEGIN PAGE LEVEL PLUGINS -->
<!-- END PAGE LEVEL PLUGINS -->
{% endblock %}

{% block content %}
<div class="page-content">
    <!-- BEGIN PAGE HEAD-->
    <div class="page-head">
        <!-- BEGIN PAGE TITLE -->
        <div class="page-title">
            <h1>{% trans "View Company" %}
                <small>{% trans "View Company" %}</small>
            </h1>
        </div>
        <!-- END PAGE TITLE -->
    </div>
    <!-- END PAGE HEAD-->
    <!-- BEGIN PAGE BREADCRUMB -->
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <a href="{% url 'webSite:home' %}">{% trans "Home" %}</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="{% url 'webSite:company_list' %}">{% trans "Company List" %}</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span class="active">{{company.name}}</span>

            </li>
        </ul>
    <!-- END PAGE BREADCRUMB -->
    <!-- BEGIN PAGE BASE CONTENT -->
        <div class="row">
            <div class="col-md-6">
                <div class="portlet light">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-building"></i>
                            <span class="caption-subject bold font-yellow-casablanca uppercase"> {% trans "Company" %} </span>
                        </div>

                    </div>
                    <div class="portlet-body">
                        <div class="row static-info">
                            <div class="col-md-5 name"> {% trans "Company name" %}</div>
                            <div class="col-md-7 value"> {{company.name}}
                            </div>
                        </div>

                        <div class="row static-info">
                            <div class="col-md-5 name"> {% trans "Company address" %}</div>
                            <div class="col-md-7 value"> {{company.address}}
                            </div>
                        </div>

                        <div class="row static-info">
                            <div class="col-md-5 name"> {% trans "Company owner" %}</div>
                            <div class="col-md-7 value"> {{company.owner}}
                            </div>
                        </div>

                          <div class="row static-info">
                            <div class="col-md-5 name"> {% trans "Company email" %}</div>
                            <div class="col-md-7 value"> {{company.email}}
                            </div>
                        </div>

                           <div class="row static-info">
                            <div class="col-md-5 name"> {% trans "Company phone" %}</div>
                            <div class="col-md-7 value"> {{company.phone}}
                            </div>
                        </div>

                          <div class="row static-info">
                            <div class="col-md-5 name"> {% trans "Bio" %}</div>
                            <div class="col-md-7 value"> {{company.bio}}
                            </div>
                        </div>

                          <div class="row static-info">
                            <div class="col-md-5 name"> {% trans "Date of creation" %}</div>
                            <div class="col-md-7 value"> {{company.created_at}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>

<!--            <div class="col-md-6">-->
<!--                  <div class="portlet light">-->
<!--                    <div class="portlet-title">-->
<!--                        <div class="caption">-->
<!--                            <i class="fa fa-users"></i>-->
<!--                            <span class="caption-subject bold font-yellow-casablanca uppercase"> {% trans "Documents " %} </span>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <div class="portlet-body">-->
<!--                        <div class="row static-info">-->
<!--                            <div class="col-md-6 col-xs-4 col-lg-4 col-md-4  col-sm-4">-->
<!--                            </div>-->
<!--                        </div>-->
                        <div class="row static-info">
                            <div class="col-md-5 name">{% trans '' %} </div>
                            <div class="col-md-7 value"> </div>
                        </div>

                        <div class="row static-info">
                            <div class="col-md-5 name">{% trans '' %} </div>
                            <div class="col-md-7 value"> </div>
                        </div>

                        <div class="row static-info">
                            <div class="col-md-5 name"> {% trans '' %} </div>
                            <div class="col-md-7 value"> </div>
                        </div></div>

                    </div>
                </div>
        </div>
</div>
    <!-- END PAGE BASE CONTENT -->

<nav class="quick-nav">
    <a class="quick-nav-trigger" href="#0">
        <span aria-hidden="true"></span>
    </a>
    <ul>
        <li>
            <a href="" class="red">
                <span>{% trans "Edit" %}</span>
                <i class="fa fa-pencil"></i>
            </a>
        </li>
        <li>
            <a href="" class="default">
                <span>{% trans "Cancel" %}</span>
                <i class="fa fa-times"></i>
            </a>
        </li>
    </ul>
    <span aria-hidden="true" class="quick-nav-bg"></span>
</nav>
<div class="quick-nav-overlay"></div>

{% endblock %}
{% block specific_js %}
<!-- BEGIN PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{% static '../assets/pages/scripts/form-samples.min.js' % }" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="../assets/global/plugins/bootstrap-fileinput/c" type="text/javascript"></script>
<script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>
<script src="../assets/global/plugins/gmaps/gmaps.min.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<script>
            $(document).ready(function()
            {
                $('#clickmewow').click(function()
                {
                    $('#radio1003').attr('checked', 'checked');
                });
            })
</script>

{% endblock %}

gym/webSite/templates/webSite/gym_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% load staticfiles %}
{% block title %} {% trans "View Company Info" %} {% endblock %}
{% block specific_css %}
<!-- BEGIN PAGE LEVEL PLUGINS -->
<!-- END PAGE LEVEL PLUGINS -->
{% endblock %}

{% block content %}
<div class="page-content">
    <!-- BEGIN PAGE HEAD-->
    <div class="page-head">
        <!-- BEGIN PAGE TITLE -->
        <div class="page-title">
            <h1>{% trans "View Gym" %}
                <small>{% trans "View Gym" %}</small>
            </h1>
        </div>
        <!-- END PAGE TITLE -->
    </div>
    <!-- END PAGE HEAD-->
    <!-- BEGIN PAGE BREADCRUMB -->
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <a href="{% url 'webSite:home' %}">{% trans "Home" %}</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <a href="{% url 'webSite:gym_list' %}">{% trans "Gym List" %}</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span class="active">{{gym.name}}</span>

            </li>
        </ul>
    <!-- END PAGE BREADCRUMB -->
    <!-- BEGIN PAGE BASE CONTENT -->
        <div class="row">
            <div class="col-md-6">
                <div class="portlet light">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-building"></i>
                            <span class="caption-subject bold font-yellow-casablanca uppercase"> {% trans "Gym" %} </span>
                        </div>

                    </div>
                    <div class="portlet-body">
                        <div class="row static-info">
                            <div class="col-md-5 name"> {% trans "Gym name" %}</div>
                            <div class="col-md-7 value"> {{gym.name}}
                            </div>
                        </div>

                        <div class="row static-info">
                            <div class="col-md-5 name"> {% trans "Gym user" %}</div>
                            <div class="col-md-7 value"> {{gym.user}}
                            </div>
                        </div>

                        <div class="row static-info">
                            <div class="col-md-5 name"> {% trans "Gym belongs to company" %}</div>
                            <div class="col-md-7 value"> {{gym.company}}
                            </div>
                        </div>

                          <div class="row static-info">
                            <div class="col-md-5 name"> {% trans "Gym location" %}</div>
                            <div class="col-md-7 value"> {{gym.location}}
                            </div>
                        </div>

                         <div class="row static-info">
                            <div class="col-md-5 name"> {% trans "Gym email" %}</div>
                            <div class="col-md-7 value"> {{gym.email}}
                            </div>
                        </div>

                          <div class="row static-info">
                            <div class="col-md-5 name"> {% trans "Gym phone" %}</div>
                            <div class="col-md-7 value"> {{gym.phone}}
                            </div>
                        </div>

                          <div class="row static-info">
                            <div class="col-md-5 name"> {% trans "Bio" %}</div>
                            <div class="col-md-7 value"> {{gym.bio}}
                            </div>
                        </div>

                        </div>
                    </div>
                </div>
            </div>

<!--            <div class="col-md-6">-->
<!--                  <div class="portlet light">-->
<!--                    <div class="portlet-title">-->
<!--                        <div class="caption">-->
<!--                            <i class="fa fa-users"></i>-->
<!--                            <span class="caption-subject bold font-yellow-casablanca uppercase"> {% trans "Documents " %} </span>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                    <div class="portlet-body">-->
<!--                        <div class="row static-info">-->
<!--                            <div class="col-md-6 col-xs-4 col-lg-4 col-md-4  col-sm-4">-->
<!--                            </div>-->
<!--                        </div>-->
                        <div class="row static-info">
                            <div class="col-md-5 name">{% trans '' %} </div>
                            <div class="col-md-7 value"> </div>
                        </div>

                        <div class="row static-info">
                            <div class="col-md-5 name">{% trans '' %} </div>
                            <div class="col-md-7 value"> </div>
                        </div>

                        <div class="row static-info">
                            <div class="col-md-5 name"> {% trans '' %} </div>
                            <div class="col-md-7 value"> </div>
                        </div></div>

                    </div>
                </div>
        </div>
</div>
    <!-- END PAGE BASE CONTENT -->

<nav class="quick-nav">
    <a class="quick-nav-trigger" href="#0">
        <span aria-hidden="true"></span>
    </a>
    <ul>
        <li>
            <a href="" class="red">
                <span>{% trans "Edit" %}</span>
                <i class="fa fa-pencil"></i>
            </a>
        </li>
        <li>
            <a href="" class="default">
                <span>{% trans "Cancel" %}</span>
                <i class="fa fa-times"></i>
            </a>
        </li>
    </ul>
    <span aria-hidden="true" class="quick-nav-bg"></span>
</nav>
<div class="quick-nav-overlay"></div>

{% endblock %}
{% block specific_js %}
<!-- BEGIN PAGE LEVEL PLUGINS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="{% static '../assets/pages/scripts/form-samples.min.js' % }" type="text/javascript"></script>
<!-- END PAGE LEVEL SCRIPTS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="../assets/global/plugins/bootstrap-fileinput/c" type="text/javascript"></script>
<script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>
<script src="../assets/global/plugins/gmaps/gmaps.min.js" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<script>
            $(document).ready(function()
            {
                $('#clickmewow').click(function()
                {
                    $('#radio1003').attr('checked', 'checked');
                });
            })
</script>

{% endblock %}

gym/webSite/templates/webSite/user_settings.html
{% load staticfiles %}
{% load i18n %}
{% load show_error_forms%}

<div id="tab_3-3" class="tab-pane">

    <form action="{% url 'accounts:user-change-password' %}" class="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label class="control-label">{% trans 'Current Password' %}</label>

            {{ password_form.old_password}}

        </div>
        <div class="form-group">
            <label class="control-label">{% trans 'New Password' %}</label>
            {{ password_form.new_password1 }}
        </div>
        <div class="form-group">
            <label class="control-label">{% trans 'Re-type New Password' %}</label>
            {{ password_form.new_password2 }}
        </div>
        <div class="margin-top-10">
            <button type="submit" class="btn green pull-right" class="btn green"> {% trans "SAVES CHANGES" %}</button>
            <a href="{% url 'accounts:home'   %}" class="btn default pull-right">{% trans 'Cancel' %} </a>
        </div>
    </form>
</div>
<div id="tab_4-4" class="tab-pane">
    <form action="{% url 'accounts:user-change-privacy-settings'  %}" method="POST" class="">
        {% csrf_token %}
        <div class="mt-radio-inline">
            <table class="table table-bordered table-striped">
                <tr>
                    <td> {% trans "Would you like to receive emails ?" %}</td>
                    <td>
                        <div class="mt-radio-inline">
                            <label class="mt-radio">
                                {{ps_form.receive_email}}
                            </label>
                        </div>

                    </td>
                </tr>
                <tr>
                    <td> {% trans "Would you like to receive IMS ?" %}</td>
                    <td>
                        <div class="mt-radio-inline">
                            <label class="mt-radio">
                                {{ps_form.receive_message}}
                            </label>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
        <!--end profile-settings-->
        <div class="margin-top-10">
            <button type="submit" class="btn green pull-right" class="btn green"> {% trans "Saves changes" %}</button>
            <a href="{% url 'accounts:home'   %}" class="btn default pull-right">{% trans "Cancel" %} </a>
        </div>
    </form>
</div>